import type { Metadata } from 'next';
import { Bricolage_Grotesque, DM_Sans } from 'next/font/google';
import './globals.css';
import StoreProvider from '@/lib/providers/StoreProvider';

const bricolage = Bricolage_Grotesque({
	variable: '--bricolage',
	subsets: ['latin'],
});

const dmSans = DM_Sans({
	variable: '--font-dm',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${bricolage.variable} ${dmSans.variable} antialiased`}>
				<StoreProvider>{children}</StoreProvider>
			</body>
		</html>
	);
}
